### ISSUE TITLE
Backend/Datenbank: Die Bestellung sollte korrekt eingegegeben werden

### ISSUE THREAD

**Issue by Weyaaron** [Weyaaron/AbschlussProjektB-H#26]
Momentan macht die orders.php inhaltlich Unsinn. Wir sollten sie verbessern damit wir mittelfristig neue Features implementieren können. 
Insbesondere sollten wir verbessern, dass die vom Frontend gelieferten Mengen und Eissorten korrekt in der Datenbank landen sowie Support für mehrere Eissorten pro Bestellung implementieren.

**Comment by MaPankow** [comment]
In Issue #23 habe ich einen Kommentar geschrieben, dass ich dort gern die Anzahl pro MenuItems in die Tabelle OrderItems eingeben würde. Momentan wird der Wert übergeben, der neben "Bestellung aufgeben" ist.
Das würde ich gern ändern und über dieses Feld den Gesamtpreis in die DB eintragen. (Für dieses Issue hart codiert) Der Gesamtpreis braucht allerdings noch einen Ort, wo er gespeichert werden kann, dafür würde ich eine Spalte "total_price" in der Tabelle orders vorschlagen.

**Comment by Weyaaron** [comment]
Ich würde diese Eingabe komplett entfernen. Also dann in einem separaten PR fürs Frontend. Total Price sollten wir nicht speichern, weil wir ihn aus den restlichen Datenbank-Daten  rekonstruieren können, ihn anzulegen wäre eine Redundanz

**Comment by MaPankow** [comment]
Also kommt dieses Feld neben dem Button komplett weg? Oder erst mal zusammen mit Waffel/Becher auskommentieren? Das steht ja auch noch da und ich würde es erst mal auskommentieren wollen, bis wir entscheiden, ob wir es noch nutzen wollen. Das wäre m. E. was, was wir später machen können.
Ich verstehe das jetzt so, als Akzeptanzkriterium: Wenn der Bestellbutton geklickt wird, erfolgt Eintrag in die DB orderItems, u. a. mit Foreign Key Menu_Item für die Eissorte und der quantity für die jeweilige Eissorte (die Zahl, die im jeweiligen Dropdown-Menü ausgewählt wird).
Für den Fall, dass nur eine oder zwei Sorten ausgesucht werden, würde ich ein eigenes Issue aufmachen. Ist eigentlich nur if-else, glaube ich, aber ich will erst mal die Übergabe ans Laufen kriegen und dann weiterfummeln.

**Comment by Weyaaron** [comment]
Ich bin definitiv gegen auskommentieren, das ist sehr schlechter Stil.  Falls wir sowas nochmal brauchen gibt es dafür git. 
Das mit dem Akzeptanzkriterium ist die falsche Anlaufstelle. Es gibt aus Sicht des Backends keinen Button etc. Es gibt nur die Anfrage. 
Ich würde dich bitten das Frontend entweder nicht anzufassen oder höchstens Werte hart reinzuschreiben. Du solltest nur am Backend arbeiten. Ich kann dir mal was raussuchen wie du deine eigene Anfrage ans Backend schickst, am besten im Format von PR #37.

**Comment by Weyaaron** [comment]
Du kannst mittels curl in der Konsole deine eigenen Anfragen bauen und json mitschicken:
`curl --json '{ "drink": "coffe" }' localhost:8000/api/orders.php`
Du kannst aber natürlich auch mit postman o.ä. arbeiten.

**Comment by MaPankow** [comment]
Puuuh, so ganz weiß ich nicht, ob ich es richtig verstehe. Ich kann es versuchen, habe aber gerade viel anderen Kram um die Ohren. Ines und ich hatten uns letzten Freitag noch was länger unterhalten und wir wollten dich sowieso noch fragen, ob wir uns diesen Freitag wieder 17 Uhr in Teams treffen wollen. Ich fände es generell besser, die Issues noch mal mündlich zu besprechen, mit Schema und einigen anderen Aufgaben wird mir das ein bisschen komplex und ich muss direkte Fragen stellen, um das verstehen zu können. Würde dir Freitag 17 Uhr passen?

**Comment by Weyaaron** [comment]
Schreib mir mal bei Teams, bis Freitag ist ja noch seehr viel Zeit, da geht davor was.

**Comment by MaPankow** [comment]
Die Daten werden bis dato noch nicht vom Frontend übergeben. Um zu testen, ob sie in die DB eingetragen werden, nutze ich Thunderclient (so was wie Postman für vscode), wo ich JSON-Daten nach dem Schema eingeben kann.
