### ISSUE TITLE
Backend/Datenbank: Glatte Preise für die Eissorten

### ISSUE THREAD

**Issue by MaPankow** [Weyaaron/AbschlussProjektB-H#35]
So was wie 1.80, 2.50 etc. Im Moment stehen da krumme Preise drin.

**Comment by Weyaaron** [comment]
Meinst du damit ganze Euros? Alternativ könnte man den Wert auch als "100" speichern und damit Cent meinen. Wäre ich Fan von.

**Comment by MaPankow** [comment]
Nope, ich meine, einfach nur realistische Preise, wie 2.50 oder so. Ines und ich hatten bemerkt, dass da jetzt so komische Zahlen drinstehen. Da wäre nichts zu programmieren, einfach nur andere Preise einzutragen. Habe nur ein gesondertes Issue aufgemacht, damit das einzeln ist und nicht zusammen mit einer anderen Aufgabe von mehreren gemacht wird.
